"""
Signal and Pattern Models
Models for tracking alpha signals and pattern learning
"""

from datetime import datetime

from sqlalchemy import JSON, Column, DateTime, Float, Index, Integer, String

from .base_models import BaseLearningModel, BaseSignalModel, MarketConditionsMixin


class AlphaSignal(BaseSignalModel, MarketConditionsMixin):
    """Track alpha signals generated by the LLM system"""

    __tablename__ = "alpha_signals"

    # Signal identification
    signal_id = Column(String(100), nullable=False, unique=True, index=True)
    signal_type = Column(String(50), nullable=False, index=True)

    # Signal generation
    generation_method = Column(String(50), nullable=False)
    expected_alpha = Column(Float, nullable=False)
    time_horizon_days = Column(Integer, nullable=False)

    # Entry conditions
    entry_price_target = Column(Float, nullable=True)
    entry_conditions = Column(JSON, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)

    # Risk metrics
    estimated_volatility = Column(Float, nullable=True)
    beta_to_market = Column(Float, nullable=True)
    correlation_to_portfolio = Column(Float, nullable=True)

    # Signal status
    status = Column(String(20), default="active", index=True)
    triggered_at = Column(DateTime, nullable=True)
    closed_at = Column(DateTime, nullable=True)

    # Performance tracking
    actual_alpha_generated = Column(Float, nullable=True)
    actual_return = Column(Float, nullable=True)
    max_favorable_excursion = Column(Float, nullable=True)
    max_adverse_excursion = Column(Float, nullable=True)

    # Market context at generation
    technical_setup = Column(JSON, nullable=True)
    fundamental_factors = Column(JSON, nullable=True)

    # Reasoning and explainability
    key_factors = Column(JSON, nullable=True)

    # Timestamps
    generated_at = Column(DateTime, default=datetime.utcnow, index=True)
    expires_at = Column(DateTime, nullable=True, index=True)

    # Indexes for alpha signal tracking
    __table_args__ = (
        Index("idx_alpha_signals_active", "status", "generated_at"),
        Index("idx_alpha_signal_performance", "llm_model", "actual_alpha_generated"),
        Index("idx_signal_tracking", "symbol", "signal_type", "status"),
        Index(
            "idx_alpha_generation",
            "expected_alpha",
            "actual_alpha_generated",
            "confidence_score",
        ),
    )


class PatternLearning(BaseLearningModel):
    """Store pattern learning insights for continuous improvement"""

    __tablename__ = "pattern_learning"

    # Pattern identification
    pattern_family = Column(String(100), nullable=False, index=True)
    pattern_variant = Column(String(100), nullable=True)

    # Learning metrics
    total_occurrences = Column(Integer, default=0)
    successful_occurrences = Column(Integer, default=0)

    # Alpha generation insights
    avg_alpha_generated = Column(Float, default=0.0)
    alpha_consistency = Column(Float, default=0.0)
    best_market_conditions = Column(JSON, nullable=True)

    # Optimal parameters
    optimal_confidence_threshold = Column(Float, nullable=True)
    optimal_time_horizon = Column(String(20), nullable=True)
    optimal_position_sizing = Column(Float, nullable=True)

    # Market condition preferences
    preferred_volatility_range = Column(JSON, nullable=True)
    preferred_volume_profile = Column(String(20), nullable=True)
    preferred_market_regime = Column(String(20), nullable=True)

    # LLM specialization
    best_performing_llm = Column(String(50), nullable=True)
    llm_performance_ranking = Column(JSON, nullable=True)

    # Learning updates
    last_learning_update = Column(DateTime, default=datetime.utcnow)
    learning_sample_size = Column(Integer, default=0)
    confidence_in_learning = Column(Float, default=0.0)

    # Indexes
    __table_args__ = (
        Index(
            "idx_pattern_learning",
            "pattern_family",
            "success_rate",
            "avg_alpha_generated",
        ),
        Index("idx_learning_updates", "last_learning_update", "confidence_in_learning"),
    )
